# Generated by Django 3.0.6 on 2020-07-17 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('google', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='username',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
